export const M = {
  CHANGE_SEARCH_STR: 'CHANGE_SEARCH_STR',
  CHANGE_SEARCH_COUNT: 'CHANGE_SEARCH_COUNT',
  CHANGE_DOWNLOAD_PATH: 'CHANGE_DOWNLOAD_PATH',
  DOWNLOAD_IMAGES: 'DOWNLOAD_IMAGES',
  SEARCH_IMAGES_FROM_GOOGLE: 'SEARCH_IMAGES_FROM_GOOGLE'
}
